name: Amethyst
version: '${project.version}'
main: wtf.casper.amethyst.paper.AmethystPaper
api-version: 1.13
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
  - Lands
  - GriefPrevention
  - Floodgate
  - Vault
  - CrashClaim
  - RyseInventory
  - AdvancedVanish
  - DeluxeCombat
  - RoseStacker
  - WorldEdit
  - Towny
libraries:
  - org.mongodb:mongo-java-driver:3.12.11
  - org.quartz-scheduler:quartz:2.3.2
  - org.reflections:reflections:0.10.2
  - com.github.ben-manes.caffeine:caffeine:3.1.3
  - io.projectreactor:reactor-core:3.5.2
  - org.mariadb.jdbc:mariadb-java-client:3.1.2