name: Amethyst
version: '${project.version}'
main: wtf.casper.amethyst.paper.AmethystPaper
api-version: 1.13
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
  - Lands
  - GriefPrevention
  - Floodgate
  - Vault
  - CrashClaim
  - RyseInventory
  - AdvancedVanish
  - DeluxeCombat
  - RoseStacker
  - WorldEdit
  - Towny