name: Amethyst
version: '${project.version}'
main: wtf.casper.amethyst.paper.AmethystActual
api-version: 1.13
load: STARTUP
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
  - Lands
  - GriefPrevention
  - Floodgate
  - Vault
  - CrashClaim
  - RyseInventory
  - AdvancedVanish
  - DeluxeCombat
  - RoseStacker
  - WorldEdit
  - Towny